ODD = 1
EVEN = 2
BOTH = 3
VERY_LARGE_SCORE = 10 ** 18

MASTER_MIN_SLOT_INDEX = 5
COLUMNS_PER_GROUP = 4

MIN_CAPACITY_RATIO = 0.75
MAX_CAPACITY_RATIO = 1.0
MAX_CAPACITY_OVERFLOW = 1.1

MIN_ALLOWED_RATIO = 0.3
MAX_ALLOWED_RATIO = 3

MAX_COURSE_HOURS_PER_DAY_PER_SY = 5
MAX_TOTAL_HOURS_PER_DAY_PER_SY = 8
MAX_TOTAL_HOURS_PER_DAY_PER_TEACHER = 8
MAX_COURSE_HOURS_PER_DAY_PER_TEACHER = 4

MAX_BACHELOR_THIRD_YEAR_DAYS = 4
