GA_POPULATION = 40
GA_GENERATIONS = 10
GA_ELITES = 4
GA_TOURNAMENT_SIZE_K = 3
GA_MUTATION_RATE = 0.08
GA_MUTATION_SIGMA = 0.25
GA_CROSSOVER_RATE = 0.5

GA_CONSTRUCT_CELL_TRIES = 2200

LNS_FINAL_ITERATIONS = 400
LNS_IMPROVEMENT_ITERATIONS = 140
LNS_REMOVAL_SIZE = 22
LNS_REINSERTION_TRY_LIMIT = 2500

LNS_DESTROY_OPERATORS = ("random", "conflict", "population")
LNS_REPAIR_OPERATORS = ("greedy", "regret2")
LNS_REMOVAL_SIZE_OPTIONS = tuple(sorted({max(6, LNS_REMOVAL_SIZE - 6), LNS_REMOVAL_SIZE, LNS_REMOVAL_SIZE + 6}))

SA_INITIAL_TEMPERATURE = 35.0
SA_COOLING_RATE = 0.97
